# Generated by Django 4.2.5 on 2024-04-06 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_rating_avg_movie_rating_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='timestamps',
            new_name='timestamp',
        ),
    ]
